 SELECT *
FROM COVIDDEATH 
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

--SELECT *
--FROM [COVIDVACCINATION ]
--ORDER BY 3,4

--SELECT DATA THAT WE ARE GOING TO TO USING 

SELECT LOCATION, DATE,TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION  
FROM COVIDDEATH 
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2 


-- LOOKING AT TOTAL CASES VS TOTAL DEATHS 
-- THESE SHOWS THE POSSIBILITY OF DYING IF YOU CONTRACT THE COVIDVIRUS IN YOUR COUNTRY 
SELECT LOCATION, DATE,(CAST (TOTAL_CASES AS INT)) AS TOTAL_CASES, (CAST(TOTAL_DEATHS AS INT)) AS TOTAL_DEATHS, (CAST(TOTAL_DEATHS AS INT))/(CAST(TOTAL_CASES AS INT))*100 AS DEATHPERCENTAGE
FROM COVIDDEATH 
WHERE LOCATION LIKE '%NIGERIA%' 
AND CONTINENT IS NOT NULL
ORDER BY 1,2 


-- LOOKING AT THE TOTAL CASES VS POPULATION 
-- THIS SHOWS THE PERCENTAGE OF THE POPULATION THAT GOT COVID 

SELECT LOCATION, DATE, POPULATION,TOTAL_CASES, (TOTAL_CASES/POPULATION)*100 AS INFECTEDPOPULATIONPERCENTAGE 
FROM COVIDDEATH 
--WHERE LOCATION LIKE '%NIGERIA%' 
ORDER BY 1,2 


-- LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION 

SELECT LOCATION, POPULATION,MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT , MAX((TOTAL_CASES/POPULATION))*100 AS INFECTEDPOPULATIONPERCENTAGE
FROM COVIDDEATH 
--WHERE LOCATION LIKE '%NIGERIA%' 
GROUP BY LOCATION, POPULATION
ORDER BY INFECTEDPOPULATIONPERCENTAGE DESC


-- SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION 

SELECT LOCATION, MAX(CAST (TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT 
FROM COVIDDEATH 
--WHERE LOCATION LIKE '%NIGERIA%' 
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC

-- LET'S BREAK THINGS DOWN BY CONTINENT     


-- THIS SHOWS THE CONTINENT WITH THE HIGHEST DEATH COUNT PER POPULATION 

SELECT CONTINENT, MAX(CAST (TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT 
FROM COVIDDEATH 
--WHERE LOCATION LIKE '%NIGERIA%' 
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC 


-- GLOBAL REPRESENTATION OF NUMBERS


-- THIS SHOWS THE TOTAL NUMBER OF CASES AND THE TOTAL NUMBER OF DEATHS GLOBALLY
SELECT SUM(NEW_CASES) AS TOTAL_CASES, SUM(NEW_DEATHS) AS TOTAL_DEATHS
FROM COVIDDEATH 
--WHERE LOCATION LIKE '%NIGERIA%' 
WHERE CONTINENT IS NOT NULL
--GROUP BY DATE 
ORDER BY 1,2 

-- THIS SHOWS THE GLOBAL TOTAL NUMBER OF CASES AND THE GLOBAL TOTAL NUMBER OF DEATHS ON A DAILY BASIS
SELECT DATE, SUM(NEW_CASES) AS TOTAL_CASES, SUM(NEW_DEATHS) AS TOTAL_DEATHS
FROM COVIDDEATH 
--WHERE LOCATION LIKE '%NIGERIA%' 
WHERE CONTINENT IS NOT NULL
GROUP BY DATE 
ORDER BY 1,2 

-- LOOKING AT TOTAL POPULATION VS VACCINATION  

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS 
FROM COVIDDEATH DEA
JOIN [COVIDVACCINATION ] VAC
  ON DEA.LOCATION = VAC.LOCATION 
  AND DEA.DATE = VAC.DATE 
  WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3


-- LOOKING AT NEW VACCINATION PER DAY

SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS 
, SUM( CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--, ( ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM COVIDDEATH DEA
JOIN [COVIDVACCINATION ] VAC
  ON DEA.LOCATION = VAC.LOCATION 
  AND DEA.DATE = VAC.DATE 
  WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3 



-- USE CTE
 
 WITH POPvsVAC (CONTINENT, LOCATION, DATE, POPULATION,NEW_VACCINATIONS,ROLLINGPEOPLEVACCINATED)
 AS
 (
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS 
, SUM( CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--, ( ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM COVIDDEATH DEA
JOIN [COVIDVACCINATION ] VAC
  ON DEA.LOCATION = VAC.LOCATION 
  AND DEA.DATE = VAC.DATE 
  WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3 
)
SELECT *, ( ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM POPvsVAC 


-- CREATE VIEWS TO STORE DATA FOR VISUALIZATION LATER 

CREATE VIEW VACCINATEDPOPULATIONPERCENTAGE AS 
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS 
, SUM( CAST(VAC.NEW_VACCINATIONS AS INT)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
--, ( ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM COVIDDEATH DEA
JOIN [COVIDVACCINATION ] VAC
  ON DEA.LOCATION = VAC.LOCATION 
  AND DEA.DATE = VAC.DATE 
  WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 2,3 





